#!/usr/bin/env python

import signal
import pyexotica as exo
from numpy import array
from pyexotica.publish_trajectory import *
from time import sleep

exo.Setup.init_ros()
solver = exo.Setup.load_solver(
    '{exotica_nlopt_solver}/resources/nlopt_ik_constrained.xml')


dt = 0.01
t = 0.0
q = array([0.0]*7)
print('Publishing IK')
signal.signal(signal.SIGINT, sig_int_handler)
problem = solver.get_problem()
while True:
    try:
        problem.start_state = q
        problem.start_time = t
        q = solver.solve()[0]
        publish_pose(q, problem, t)
        sleep(dt)
        t = (t+dt) % 7.0
    except KeyboardInterrupt:
        break
